added: show student calendar
Abdelrahman0W/ejustian-cli pull request #18
Opened 2022-11-09 02:16 UTC by Abdelrahman0W

resolves #15

2022-11-09 19:01 UTC, Nawarrr commented on ej_cli/sis/sis.py
> +            'Course Type', 'Course Time', 'Course Venu',
Typo in Venu, it is spelled "venue"

2022-11-09 19:01 UTC, Nawarrr commented on ej_cli/sis/sis.py
> +                    course['Course Time'], course['Course Venu'], course['Course Instructor']
same here

2022-11-09 19:04 UTC, Nawarrr requested changes
Dear Bodzz,
Great work, Please address the comments I left you

2022-11-10 21:34 UTC, Abdelrahman0W commented on ej_cli/sis/sis.py
> +            'Course Type', 'Course Time', 'Course Venu',
Done!

2022-11-10 21:34 UTC, Abdelrahman0W commented on ej_cli/sis/sis.py
> +        for day, courses in data_table.items():
Done!

2022-11-10 21:34 UTC, Abdelrahman0W commented on ej_cli/sis/sis.py
> +                    course['Course Time'], course['Course Venu'], course['Course Instructor']
Done!

2022-11-10 21:35 UTC, Abdelrahman0W reviewed
@Nawarrr

2022-11-11 19:54 UTC, Nawarrr approved these changes

2022-11-11 19:54 UTC, merged